; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_dir = C:/Users/ACR/.platformio/build/petbionics_xiao_esp32c3
libdeps_dir = C:/Users/ACR/.platformio/libdeps/petbionics_xiao_esp32c3

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
upload_port = COM10
test_port = COM10
monitor_speed = 115200
test_speed = 115200
monitor_dtr = 0
monitor_rts = 0
lib_deps =
	bogde/HX711 @ ^0.7.5
